name: habbit_breaker
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.6.0
  firebase_auth: ^5.3.1
  provider: ^6.1.2
  persistent_bottom_nav_bar: ^6.2.1
  cloud_firestore: ^5.4.4
  flutter_localizations:
        sdk: flutter
  shared_preferences: ^2.3.2
  intl: ^0.19.0
  image_picker: ^1.1.2
  firebase_storage: ^12.3.4
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/logo.png
    - assets/flags/en.png
    - assets/flags/ar.png
    - assets/onboarding/healthy.png
    - assets/onboarding/monitor.png
    - assets/onboarding/reading.png
    
flutter_intl:
  enabled: true
